image: misfio32/golang-dind:1.21.3

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - test
  - report
    
unit-tests:
  stage: test
  script:
    - touch backend/internal/services/implementation/testService.log
    - touch backend/internal/repository/postgres_repo/testRepos.log
    - cd backend/internal/services/implementation
    - go test pet_test.go client_test.go doctor_test.go record_test.go pet.go record.go client.go doctor.go setup.go -gcflags=all=-l -tags=unit -cover -v 
    - go test pet_test.go client_test.go doctor_test.go record_test.go pet.go record.go client.go doctor.go setup.go -gcflags=all=-l -tags=unit -cover -json -v > testService.log
    - cd -
    - cd backend/internal/repository/postgres_repo
    - go test -gcflags=all=-l -tags=unit -cover -json ./... -v > testRepos.log   
  artifacts:
    paths:
      - backend/internal/services/implementation/testService.log
      - backend/internal/repository/postgres_repo/testRepos.log

int-tests:
  stage: test
  script:
    - touch backend/internal/services/implementation/testIntegration.log
    - cd backend/internal/services/implementation 
    - go test petPostgres_test.go recordPostgres_test.go pet.go record.go setup.go  -gcflags=all=-l -tags=integration -cover -coverprofile=serviceIntegration.out -json -v > testIntegration.log  
  needs:
    - unit-tests
  artifacts:
    paths:
      - backend/internal/services/implementation/testIntegration.log

e2e-test:
  stage: test
  script:
    - docker-compose down
    - docker-compose up -d
    - sleep 60
    - docker ps
    - cd e2e
    - go run main.go
    - sleep 10
    - curl -X GET "http://localhost:16686/api/traces?service=backend" > trace.json
  artifacts:
    paths:
      - e2e/trace.json
  needs:
    - int-tests
  tags:
    - shell

e2e-test-2fa:
  stage: test
  script:
    - docker-compose down
    - export VAULT_ADDR='http://127.0.0.1:8200'
    - export PASSWORD_FROM="$(vault kv get -field=password secret/emailFrom)"
    - export PASSWORD_TO="$(vault kv get -field=password secret/emailTo)"
    - docker-compose up -d
    - sleep 60
    - docker ps
    - cd e2e/client_controller
    - go test
    - docker-compose down
  needs:
    - e2e-test
  tags:
    - shell

report:
  stage: report
  script:
    - go install github.com/polnaya-katuxa/test-report@latest
    - mv backend/internal/services/implementation/testService.log testService.log || true
    - mv backend/internal/repository/postgres_repo/testRepos.log testRepos.log || true
    - mv backend/internal/services/implementation/testIntegration.log testIntegration.log || true
    - touch test.log
    - cat testService.log >> test.log || true
    - cat testRepos.log >> test.log || true
    - cat testIntegration.log >> test.log || true
    - test-report -f ./test.log -o .
  dependencies:
    - unit-tests
    - int-tests
  artifacts:
    paths:
      - report.html
      